// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/admin_types.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConsensusType identifies which consensus algorithm the node is running.
type ConsensusType int32

const (
	ConsensusType_CONSENSUS_TYPE_UNSPECIFIED ConsensusType = 0
	ConsensusType_CONSENSUS_TYPE_RAFT        ConsensusType = 1
)

// Enum value maps for ConsensusType.
var (
	ConsensusType_name = map[int32]string{
		0: "CONSENSUS_TYPE_UNSPECIFIED",
		1: "CONSENSUS_TYPE_RAFT",
	}
	ConsensusType_value = map[string]int32{
		"CONSENSUS_TYPE_UNSPECIFIED": 0,
		"CONSENSUS_TYPE_RAFT":        1,
	}
)

func (x ConsensusType) Enum() *ConsensusType {
	p := new(ConsensusType)
	*p = x
	return p
}

func (x ConsensusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsensusType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_admin_types_proto_enumTypes[0].Descriptor()
}

func (ConsensusType) Type() protoreflect.EnumType {
	return &file_v1_admin_types_proto_enumTypes[0]
}

func (x ConsensusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsensusType.Descriptor instead.
func (ConsensusType) EnumDescriptor() ([]byte, []int) {
	return file_v1_admin_types_proto_rawDescGZIP(), []int{0}
}

// NodeRole describes the node role in the cluster.
type NodeRole int32

const (
	NodeRole_NODE_ROLE_UNSPECIFIED NodeRole = 0
	NodeRole_NODE_ROLE_LEADER      NodeRole = 1
	NodeRole_NODE_ROLE_FOLLOWER    NodeRole = 2
	NodeRole_NODE_ROLE_CANDIDATE   NodeRole = 3
	NodeRole_NODE_ROLE_LEARNER     NodeRole = 4
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "NODE_ROLE_UNSPECIFIED",
		1: "NODE_ROLE_LEADER",
		2: "NODE_ROLE_FOLLOWER",
		3: "NODE_ROLE_CANDIDATE",
		4: "NODE_ROLE_LEARNER",
	}
	NodeRole_value = map[string]int32{
		"NODE_ROLE_UNSPECIFIED": 0,
		"NODE_ROLE_LEADER":      1,
		"NODE_ROLE_FOLLOWER":    2,
		"NODE_ROLE_CANDIDATE":   3,
		"NODE_ROLE_LEARNER":     4,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_admin_types_proto_enumTypes[1].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_v1_admin_types_proto_enumTypes[1]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_v1_admin_types_proto_rawDescGZIP(), []int{1}
}

// NodeStatus reflects the current health/lifecycle state of the node.
type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_STARTING    NodeStatus = 1
	NodeStatus_NODE_STATUS_HEALTHY     NodeStatus = 2
	NodeStatus_NODE_STATUS_DEGRADED    NodeStatus = 3
	NodeStatus_NODE_STATUS_UNAVAILABLE NodeStatus = 4
	NodeStatus_NODE_STATUS_STOPPING    NodeStatus = 5
	NodeStatus_NODE_STATUS_STOPPED     NodeStatus = 6
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_STARTING",
		2: "NODE_STATUS_HEALTHY",
		3: "NODE_STATUS_DEGRADED",
		4: "NODE_STATUS_UNAVAILABLE",
		5: "NODE_STATUS_STOPPING",
		6: "NODE_STATUS_STOPPED",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_STARTING":    1,
		"NODE_STATUS_HEALTHY":     2,
		"NODE_STATUS_DEGRADED":    3,
		"NODE_STATUS_UNAVAILABLE": 4,
		"NODE_STATUS_STOPPING":    5,
		"NODE_STATUS_STOPPED":     6,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_admin_types_proto_enumTypes[2].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_v1_admin_types_proto_enumTypes[2]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_admin_types_proto_rawDescGZIP(), []int{2}
}

// PeerInfo contains basic information about a peer node.
type PeerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer node identifier.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Optional peer address (host:port).
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_v1_admin_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_v1_admin_types_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_v1_admin_types_proto protoreflect.FileDescriptor

const file_v1_admin_types_proto_rawDesc = "" +
	"\n" +
	"\x14v1/admin_types.proto\x12\badmin.v1\"=\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress*H\n" +
	"\rConsensusType\x12\x1e\n" +
	"\x1aCONSENSUS_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CONSENSUS_TYPE_RAFT\x10\x01*\x83\x01\n" +
	"\bNodeRole\x12\x19\n" +
	"\x15NODE_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NODE_ROLE_LEADER\x10\x01\x12\x16\n" +
	"\x12NODE_ROLE_FOLLOWER\x10\x02\x12\x17\n" +
	"\x13NODE_ROLE_CANDIDATE\x10\x03\x12\x15\n" +
	"\x11NODE_ROLE_LEARNER\x10\x04*\xc6\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14NODE_STATUS_STARTING\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_HEALTHY\x10\x02\x12\x18\n" +
	"\x14NODE_STATUS_DEGRADED\x10\x03\x12\x1b\n" +
	"\x17NODE_STATUS_UNAVAILABLE\x10\x04\x12\x18\n" +
	"\x14NODE_STATUS_STOPPING\x10\x05\x12\x17\n" +
	"\x13NODE_STATUS_STOPPED\x10\x06B\x1bZ\x19pkg/proto/adminv1;adminpbb\x06proto3"

var (
	file_v1_admin_types_proto_rawDescOnce sync.Once
	file_v1_admin_types_proto_rawDescData []byte
)

func file_v1_admin_types_proto_rawDescGZIP() []byte {
	file_v1_admin_types_proto_rawDescOnce.Do(func() {
		file_v1_admin_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_types_proto_rawDesc), len(file_v1_admin_types_proto_rawDesc)))
	})
	return file_v1_admin_types_proto_rawDescData
}

var file_v1_admin_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_admin_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_admin_types_proto_goTypes = []any{
	(ConsensusType)(0), // 0: admin.v1.ConsensusType
	(NodeRole)(0),      // 1: admin.v1.NodeRole
	(NodeStatus)(0),    // 2: admin.v1.NodeStatus
	(*PeerInfo)(nil),   // 3: admin.v1.PeerInfo
}
var file_v1_admin_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_admin_types_proto_init() }
func file_v1_admin_types_proto_init() {
	if File_v1_admin_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_types_proto_rawDesc), len(file_v1_admin_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_admin_types_proto_goTypes,
		DependencyIndexes: file_v1_admin_types_proto_depIdxs,
		EnumInfos:         file_v1_admin_types_proto_enumTypes,
		MessageInfos:      file_v1_admin_types_proto_msgTypes,
	}.Build()
	File_v1_admin_types_proto = out.File
	file_v1_admin_types_proto_goTypes = nil
	file_v1_admin_types_proto_depIdxs = nil
}
