// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/admin_raft.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RaftPeerInfo contains leader-side replication info for a Raft peer.
type RaftPeerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer node identifier.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Replication status from leader perspective.
	Status NodeStatus `protobuf:"varint,2,opt,name=status,proto3,enum=admin.v1.NodeStatus" json:"status,omitempty"`
	// Highest log index known to be replicated on the peer.
	MatchIndex int64 `protobuf:"varint,3,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	// Next log index the leader will try to send.
	NextIndex int64 `protobuf:"varint,4,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	// Replication lag in entries (best-effort).
	Lag           int64 `protobuf:"varint,5,opt,name=lag,proto3" json:"lag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftPeerInfo) Reset() {
	*x = RaftPeerInfo{}
	mi := &file_v1_admin_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftPeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftPeerInfo) ProtoMessage() {}

func (x *RaftPeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftPeerInfo.ProtoReflect.Descriptor instead.
func (*RaftPeerInfo) Descriptor() ([]byte, []int) {
	return file_v1_admin_raft_proto_rawDescGZIP(), []int{0}
}

func (x *RaftPeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RaftPeerInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *RaftPeerInfo) GetMatchIndex() int64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

func (x *RaftPeerInfo) GetNextIndex() int64 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

func (x *RaftPeerInfo) GetLag() int64 {
	if x != nil {
		return x.Lag
	}
	return 0
}

// RaftNodeInfo contains Raft-specific state for the node.
type RaftNodeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current Raft term.
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Current known leader node ID, if any.
	LeaderId string `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// Highest committed log index.
	CommitIndex int64 `protobuf:"varint,3,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	// Highest log index applied to the state machine.
	LastApplied int64 `protobuf:"varint,4,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	// Last local log index.
	LastLogIndex int64 `protobuf:"varint,5,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	// Term of the last local log entry.
	LastLogTerm int64 `protobuf:"varint,6,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	// Snapshot metadata: last included index.
	SnapshotLastIndex int64 `protobuf:"varint,7,opt,name=snapshot_last_index,json=snapshotLastIndex,proto3" json:"snapshot_last_index,omitempty"`
	// Snapshot metadata: last included term.
	SnapshotLastTerm int64 `protobuf:"varint,8,opt,name=snapshot_last_term,json=snapshotLastTerm,proto3" json:"snapshot_last_term,omitempty"`
	// Snapshot size in bytes (best-effort).
	SnapshotSizeBytes int64 `protobuf:"varint,9,opt,name=snapshot_size_bytes,json=snapshotSizeBytes,proto3" json:"snapshot_size_bytes,omitempty"`
	// Leader-side peer replication state (usually empty on followers).
	Peers []*RaftPeerInfo `protobuf:"bytes,10,rep,name=peers,proto3" json:"peers,omitempty"`
	// Time when the last command/snapshot was applied to the state machine.
	LastAppliedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_applied_at,json=lastAppliedAt,proto3" json:"last_applied_at,omitempty"`
	// Active Raft cluster membership used for quorum calculation.
	ClusterMembers []string `protobuf:"bytes,12,rep,name=cluster_members,json=clusterMembers,proto3" json:"cluster_members,omitempty"`
	// Majority quorum size for the active cluster membership.
	QuorumSize    int32 `protobuf:"varint,13,opt,name=quorum_size,json=quorumSize,proto3" json:"quorum_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftNodeInfo) Reset() {
	*x = RaftNodeInfo{}
	mi := &file_v1_admin_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftNodeInfo) ProtoMessage() {}

func (x *RaftNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftNodeInfo.ProtoReflect.Descriptor instead.
func (*RaftNodeInfo) Descriptor() ([]byte, []int) {
	return file_v1_admin_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RaftNodeInfo) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftNodeInfo) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *RaftNodeInfo) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *RaftNodeInfo) GetLastApplied() int64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *RaftNodeInfo) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RaftNodeInfo) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *RaftNodeInfo) GetSnapshotLastIndex() int64 {
	if x != nil {
		return x.SnapshotLastIndex
	}
	return 0
}

func (x *RaftNodeInfo) GetSnapshotLastTerm() int64 {
	if x != nil {
		return x.SnapshotLastTerm
	}
	return 0
}

func (x *RaftNodeInfo) GetSnapshotSizeBytes() int64 {
	if x != nil {
		return x.SnapshotSizeBytes
	}
	return 0
}

func (x *RaftNodeInfo) GetPeers() []*RaftPeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RaftNodeInfo) GetLastAppliedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAppliedAt
	}
	return nil
}

func (x *RaftNodeInfo) GetClusterMembers() []string {
	if x != nil {
		return x.ClusterMembers
	}
	return nil
}

func (x *RaftNodeInfo) GetQuorumSize() int32 {
	if x != nil {
		return x.QuorumSize
	}
	return 0
}

var File_v1_admin_raft_proto protoreflect.FileDescriptor

const file_v1_admin_raft_proto_rawDesc = "" +
	"\n" +
	"\x13v1/admin_raft.proto\x12\badmin.v1\x1a\x14v1/admin_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\fRaftPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.admin.v1.NodeStatusR\x06status\x12\x1f\n" +
	"\vmatch_index\x18\x03 \x01(\x03R\n" +
	"matchIndex\x12\x1d\n" +
	"\n" +
	"next_index\x18\x04 \x01(\x03R\tnextIndex\x12\x10\n" +
	"\x03lag\x18\x05 \x01(\x03R\x03lag\"\x99\x04\n" +
	"\fRaftNodeInfo\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12!\n" +
	"\fcommit_index\x18\x03 \x01(\x03R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\x04 \x01(\x03R\vlastApplied\x12$\n" +
	"\x0elast_log_index\x18\x05 \x01(\x03R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x06 \x01(\x03R\vlastLogTerm\x12.\n" +
	"\x13snapshot_last_index\x18\a \x01(\x03R\x11snapshotLastIndex\x12,\n" +
	"\x12snapshot_last_term\x18\b \x01(\x03R\x10snapshotLastTerm\x12.\n" +
	"\x13snapshot_size_bytes\x18\t \x01(\x03R\x11snapshotSizeBytes\x12,\n" +
	"\x05peers\x18\n" +
	" \x03(\v2\x16.admin.v1.RaftPeerInfoR\x05peers\x12B\n" +
	"\x0flast_applied_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rlastAppliedAt\x12'\n" +
	"\x0fcluster_members\x18\f \x03(\tR\x0eclusterMembers\x12\x1f\n" +
	"\vquorum_size\x18\r \x01(\x05R\n" +
	"quorumSizeB\x1bZ\x19pkg/proto/adminv1;adminpbb\x06proto3"

var (
	file_v1_admin_raft_proto_rawDescOnce sync.Once
	file_v1_admin_raft_proto_rawDescData []byte
)

func file_v1_admin_raft_proto_rawDescGZIP() []byte {
	file_v1_admin_raft_proto_rawDescOnce.Do(func() {
		file_v1_admin_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_raft_proto_rawDesc), len(file_v1_admin_raft_proto_rawDesc)))
	})
	return file_v1_admin_raft_proto_rawDescData
}

var file_v1_admin_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_admin_raft_proto_goTypes = []any{
	(*RaftPeerInfo)(nil),          // 0: admin.v1.RaftPeerInfo
	(*RaftNodeInfo)(nil),          // 1: admin.v1.RaftNodeInfo
	(NodeStatus)(0),               // 2: admin.v1.NodeStatus
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_admin_raft_proto_depIdxs = []int32{
	2, // 0: admin.v1.RaftPeerInfo.status:type_name -> admin.v1.NodeStatus
	0, // 1: admin.v1.RaftNodeInfo.peers:type_name -> admin.v1.RaftPeerInfo
	3, // 2: admin.v1.RaftNodeInfo.last_applied_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_admin_raft_proto_init() }
func file_v1_admin_raft_proto_init() {
	if File_v1_admin_raft_proto != nil {
		return
	}
	file_v1_admin_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_raft_proto_rawDesc), len(file_v1_admin_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_admin_raft_proto_goTypes,
		DependencyIndexes: file_v1_admin_raft_proto_depIdxs,
		MessageInfos:      file_v1_admin_raft_proto_msgTypes,
	}.Build()
	File_v1_admin_raft_proto = out.File
	file_v1_admin_raft_proto_goTypes = nil
	file_v1_admin_raft_proto_depIdxs = nil
}
