// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetNodeInfoRequest requests info about the current node.
type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{0}
}

// GetNodeInfoResponse contains administrative node information.
type GetNodeInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current node information.
	Node          *NodeInfo `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeInfoResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_v1_admin_proto protoreflect.FileDescriptor

const file_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/admin.proto\x12\badmin.v1\x1a\x13v1/admin_node.proto\"\x14\n" +
	"\x12GetNodeInfoRequest\"=\n" +
	"\x13GetNodeInfoResponse\x12&\n" +
	"\x04node\x18\x01 \x01(\v2\x12.admin.v1.NodeInfoR\x04node2Z\n" +
	"\fAdminService\x12J\n" +
	"\vGetNodeInfo\x12\x1c.admin.v1.GetNodeInfoRequest\x1a\x1d.admin.v1.GetNodeInfoResponseB\x1bZ\x19pkg/proto/adminv1;adminpbb\x06proto3"

var (
	file_v1_admin_proto_rawDescOnce sync.Once
	file_v1_admin_proto_rawDescData []byte
)

func file_v1_admin_proto_rawDescGZIP() []byte {
	file_v1_admin_proto_rawDescOnce.Do(func() {
		file_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)))
	})
	return file_v1_admin_proto_rawDescData
}

var file_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_admin_proto_goTypes = []any{
	(*GetNodeInfoRequest)(nil),  // 0: admin.v1.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil), // 1: admin.v1.GetNodeInfoResponse
	(*NodeInfo)(nil),            // 2: admin.v1.NodeInfo
}
var file_v1_admin_proto_depIdxs = []int32{
	2, // 0: admin.v1.GetNodeInfoResponse.node:type_name -> admin.v1.NodeInfo
	0, // 1: admin.v1.AdminService.GetNodeInfo:input_type -> admin.v1.GetNodeInfoRequest
	1, // 2: admin.v1.AdminService.GetNodeInfo:output_type -> admin.v1.GetNodeInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_admin_proto_init() }
func file_v1_admin_proto_init() {
	if File_v1_admin_proto != nil {
		return
	}
	file_v1_admin_node_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_proto_goTypes,
		DependencyIndexes: file_v1_admin_proto_depIdxs,
		MessageInfos:      file_v1_admin_proto_msgTypes,
	}.Build()
	File_v1_admin_proto = out.File
	file_v1_admin_proto_goTypes = nil
	file_v1_admin_proto_depIdxs = nil
}
