// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/admin_node.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeInfo contains administrative information about the current node.
type NodeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NodeID
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// ConsensusType
	ConsensusType ConsensusType `protobuf:"varint,2,opt,name=consensus_type,json=consensusType,proto3,enum=admin.v1.ConsensusType" json:"consensus_type,omitempty"`
	// Role
	Role NodeRole `protobuf:"varint,3,opt,name=role,proto3,enum=admin.v1.NodeRole" json:"role,omitempty"`
	// Status
	Status NodeStatus `protobuf:"varint,4,opt,name=status,proto3,enum=admin.v1.NodeStatus" json:"status,omitempty"`
	// Peers
	Peers []*PeerInfo `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	// Consensus-specific details.
	//
	// Types that are valid to be assigned to ConsensusDetails:
	//
	//	*NodeInfo_Raft
	ConsensusDetails isNodeInfo_ConsensusDetails `protobuf_oneof:"consensus_details"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_v1_admin_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_v1_admin_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetConsensusType() ConsensusType {
	if x != nil {
		return x.ConsensusType
	}
	return ConsensusType_CONSENSUS_TYPE_UNSPECIFIED
}

func (x *NodeInfo) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_NODE_ROLE_UNSPECIFIED
}

func (x *NodeInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeInfo) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NodeInfo) GetConsensusDetails() isNodeInfo_ConsensusDetails {
	if x != nil {
		return x.ConsensusDetails
	}
	return nil
}

func (x *NodeInfo) GetRaft() *RaftNodeInfo {
	if x != nil {
		if x, ok := x.ConsensusDetails.(*NodeInfo_Raft); ok {
			return x.Raft
		}
	}
	return nil
}

type isNodeInfo_ConsensusDetails interface {
	isNodeInfo_ConsensusDetails()
}

type NodeInfo_Raft struct {
	Raft *RaftNodeInfo `protobuf:"bytes,6,opt,name=raft,proto3,oneof"`
}

func (*NodeInfo_Raft) isNodeInfo_ConsensusDetails() {}

var File_v1_admin_node_proto protoreflect.FileDescriptor

const file_v1_admin_node_proto_rawDesc = "" +
	"\n" +
	"\x13v1/admin_node.proto\x12\badmin.v1\x1a\x14v1/admin_types.proto\x1a\x13v1/admin_raft.proto\"\xa6\x02\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12>\n" +
	"\x0econsensus_type\x18\x02 \x01(\x0e2\x17.admin.v1.ConsensusTypeR\rconsensusType\x12&\n" +
	"\x04role\x18\x03 \x01(\x0e2\x12.admin.v1.NodeRoleR\x04role\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.admin.v1.NodeStatusR\x06status\x12(\n" +
	"\x05peers\x18\x05 \x03(\v2\x12.admin.v1.PeerInfoR\x05peers\x12,\n" +
	"\x04raft\x18\x06 \x01(\v2\x16.admin.v1.RaftNodeInfoH\x00R\x04raftB\x13\n" +
	"\x11consensus_detailsB\x1bZ\x19pkg/proto/adminv1;adminpbb\x06proto3"

var (
	file_v1_admin_node_proto_rawDescOnce sync.Once
	file_v1_admin_node_proto_rawDescData []byte
)

func file_v1_admin_node_proto_rawDescGZIP() []byte {
	file_v1_admin_node_proto_rawDescOnce.Do(func() {
		file_v1_admin_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_node_proto_rawDesc), len(file_v1_admin_node_proto_rawDesc)))
	})
	return file_v1_admin_node_proto_rawDescData
}

var file_v1_admin_node_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_admin_node_proto_goTypes = []any{
	(*NodeInfo)(nil),     // 0: admin.v1.NodeInfo
	(ConsensusType)(0),   // 1: admin.v1.ConsensusType
	(NodeRole)(0),        // 2: admin.v1.NodeRole
	(NodeStatus)(0),      // 3: admin.v1.NodeStatus
	(*PeerInfo)(nil),     // 4: admin.v1.PeerInfo
	(*RaftNodeInfo)(nil), // 5: admin.v1.RaftNodeInfo
}
var file_v1_admin_node_proto_depIdxs = []int32{
	1, // 0: admin.v1.NodeInfo.consensus_type:type_name -> admin.v1.ConsensusType
	2, // 1: admin.v1.NodeInfo.role:type_name -> admin.v1.NodeRole
	3, // 2: admin.v1.NodeInfo.status:type_name -> admin.v1.NodeStatus
	4, // 3: admin.v1.NodeInfo.peers:type_name -> admin.v1.PeerInfo
	5, // 4: admin.v1.NodeInfo.raft:type_name -> admin.v1.RaftNodeInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_admin_node_proto_init() }
func file_v1_admin_node_proto_init() {
	if File_v1_admin_node_proto != nil {
		return
	}
	file_v1_admin_types_proto_init()
	file_v1_admin_raft_proto_init()
	file_v1_admin_node_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeInfo_Raft)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_node_proto_rawDesc), len(file_v1_admin_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_admin_node_proto_goTypes,
		DependencyIndexes: file_v1_admin_node_proto_depIdxs,
		MessageInfos:      file_v1_admin_node_proto_msgTypes,
	}.Build()
	File_v1_admin_node_proto = out.File
	file_v1_admin_node_proto_goTypes = nil
	file_v1_admin_node_proto_depIdxs = nil
}
