// Code generated by MockGen. DO NOT EDIT.
// Source: peer_client.go

// Package raft is a generated GoMock package.
package raft

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPeerClient is a mock of PeerClient interface.
type MockPeerClient struct {
	ctrl     *gomock.Controller
	recorder *MockPeerClientMockRecorder
}

// MockPeerClientMockRecorder is the mock recorder for MockPeerClient.
type MockPeerClientMockRecorder struct {
	mock *MockPeerClient
}

// NewMockPeerClient creates a new mock instance.
func NewMockPeerClient(ctrl *gomock.Controller) *MockPeerClient {
	mock := &MockPeerClient{ctrl: ctrl}
	mock.recorder = &MockPeerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerClient) EXPECT() *MockPeerClientMockRecorder {
	return m.recorder
}

// AppendEntries mocks base method.
func (m *MockPeerClient) AppendEntries(ctx context.Context, req *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendEntries", ctx, req)
	ret0, _ := ret[0].(*AppendEntriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendEntries indicates an expected call of AppendEntries.
func (mr *MockPeerClientMockRecorder) AppendEntries(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEntries", reflect.TypeOf((*MockPeerClient)(nil).AppendEntries), ctx, req)
}

// Close mocks base method.
func (m *MockPeerClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPeerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPeerClient)(nil).Close))
}

// InstallSnapshot mocks base method.
func (m *MockPeerClient) InstallSnapshot(ctx context.Context, req *InstallSnapshotRequest) (*InstallSnapshotResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallSnapshot", ctx, req)
	ret0, _ := ret[0].(*InstallSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallSnapshot indicates an expected call of InstallSnapshot.
func (mr *MockPeerClientMockRecorder) InstallSnapshot(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallSnapshot", reflect.TypeOf((*MockPeerClient)(nil).InstallSnapshot), ctx, req)
}

// RequestVote mocks base method.
func (m *MockPeerClient) RequestVote(ctx context.Context, req *RequestVoteRequest) (*RequestVoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestVote", ctx, req)
	ret0, _ := ret[0].(*RequestVoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestVote indicates an expected call of RequestVote.
func (mr *MockPeerClientMockRecorder) RequestVote(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestVote", reflect.TypeOf((*MockPeerClient)(nil).RequestVote), ctx, req)
}
